spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/order #db order
    username: imavazq
    password: imavazq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create #No usamos flyway. Hibernate crea bd de cero cada vez que iniciamos app
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092 #direccion server kafka broker
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #convierte clave String serializada (formato binario)
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer #convierte value a enviar (OrderConfirmation) a tipo JSON
      properties:
        #producer necesita informar al consumer del topic cual es el objeto que le enviamos
        #en formato JSON para mapearlo al objeto correspondiente
        spring.json.type.mapping: orderConfirmation:com.imavazq.ecommerce.kafka.OrderConfirmation
server:
  port: 8070

application:
  config: #definimos url para conectarnos a los otros microservicios
    #Usamos puerto de API Gateway
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments