spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/product #db product
    username: imavazq
    password: imavazq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate #dejamos que Flyway cree la bd automaticamente al levantar
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true #para que cuando la bd este vacia cree una linea base desde version especificada (0)
    enabled: true
    baseline-description: "Init"
    baseline-version: 0
    user: ${spring.datasource.username} #hacemos ref dinamica xq tiene que ser el mismo user y pass para que conecte flyway
    password: ${spring.datasource.password}
server:
  port: 8050