spring:
  application:
    name: order-service #nombre app que sera referenciado para llamar a este service
  config:
    import: optional:configserver:http://localhost:8888 #indicamos que traemos la configuracion del configserver