services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:16
    environment:
      POSTGRES_USER: imavazq
      POSTGRES_PASSWORD: imavazq
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - microservices-net
    restart: unless-stopped

  #  pgadmin: #DESCOMENTAR SI NO SE TIENE INSTALADO PGADMIN4
  #    container_name: ms_pgadmin
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
  #      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    volumes:
  #      - pgadmin:/var/lib/pgadmin
  #    ports:
  #      - 5050:80
  #    networks:
  #      - microservices-net
  #    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: imavazq
      MONGO_INITDB_ROOT_PASSWORD: imavazq

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: imavazq
      ME_CONFIG_MONGODB_ADMINPASSWORD: imavazq
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: 'false'
      #ME_CONFIG_BASICAUTH_USERNAME: imavazq
      #ME_CONFIG_BASICAUTH_PASSWORD: imavazq

#    mail-dev: #Para envio de mails Notification service
#      container_name: ms_mail_dev
#      image: maildev/maildev
#      ports:
#        - 1080:1080
#        - 1025:1025 #SMTP server

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: